import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "../utils/api";
import React, { useState, useEffect } from 'react';
import { fetchResponse } from './index';

const Prompter: NextPage = () => {
  const [response, setResponse] = useState('');

  useEffect(() => {
    fetchResponse().then(res => setResponse(res));
  }, []);

  return (
    <>
      <Head>
        <title>Prompt Results</title>
        <meta name="description" content="Created by T3. Generated by OpenAI."/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-white">
        <div className="flex flex-col items-center justify-center">
            <h1 className="text-3xl font-bold text-center text-[#4C3549]">Prompt Results</h1>
            <p className="text-lg text-center text-[#883955]">What we got from your input:</p>
            <div className="w-3/4 text-2xl">
            <p>GRRRRRRRRRRRAAAAA {response1}</p>
            </div>
        </div>
      </main>
    </>
  );
};

export default Prompter;