import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "../utils/api";
import React, { useState, useEffect } from 'react';
import { fetchResponse } from './index';

const Prompter: NextPage = () => {
  const [response, setResponse] = useState('');

  // useEffect(() => {
  //   fetchResponse().then(res => setResponse(res));
  // }, []);

  return (
    <>
      <Head>
        <title>Prompt Results</title>
        <meta name="description" content="Created by T3. Generated by OpenAI."/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-[#EDE3FD]">
        <div className="flex flex-col items-center justify-center">
            <h1 className="text-3xl font-bold text-center py-8 text-[#4C3549]">Prompt Results</h1>
            <p className="text-lg text-1xl font-bold text-center text-[#351C3F]">Some questions you could ask your connection:</p>
            <div className="rounded-lg shadow-lg bg-white mt-5 mx-12 mb-10 overflow-wrap">
                <div className="p-6 text-center bg-[#5c5552] rounded-lg">
                    <p className="text-white text-base mb-4 p-5">
                        GRRRRRRR 1. Newcomers to networking need a beginner-friendly platform like a bridge that connects them to professional networking because starting a network can be intimidating. <br/>
                        2. Semi-experienced individuals who have a network but still feel intimidated by <br/> the barrier to entry need a more accessible and less formal way to connect with industry professionals because traditional networking methods can be overwhelming.<br/>
                        {response}
                        What led you to pursue a degree in Neuroscience at Johns Hopkins University?
                        <br/>
                        What are your current research interests within the field of Neuroscience?
                        <br/>
                        Can you tell me about your experience as a Research Assistant and Neuroscience Specialist?
                        <br/>
                        How did your experiences as a Vice President/Treasurer of Venturing Crew 333, Vice President of Student Recruitment for Princeton Learning Experience, and Co-Captain/Secretary of the Physics Team at Arcadia High School shape your leadership skills?
                        <br/>
                        What did you gain from your experience as a Student Volunteer at Methodist Hospital and participant at the Shadowing Program at LAC-USC MED CENTER?
                        <br/>
                        What are some of the challenges you faced during your experiences as a Junior Volunteer at LAC-USC MED CENTER?
                        <br/>
                        Can you share any projects or accomplishments that youre particularly proud of from your time at Arcadia High School?
                        <br/>
                        What are your future career aspirations within the field of Neuroscience?
                        <br/>
                        Can you tell me more about your experience teaching English online to foreign low-income students at Princeton Learning Experience?
                        <br/>
                        How did your experience volunteering at Methodist Hospital and LAC-USC MED CENTER impact your perspective on the healthcare industry?
                    </p>
                </div>
            </div>
        </div>
        <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20 bg-[#171738]"
              href="/"
              //target="_blank"
            >
              <h3 className="text-1xl font-semibold">Back to search →</h3>
            </Link>
      </main>
    </>
  );
};

export default Prompter;